level Elementary {
    title: "Elementary"
    value:1
}
level Weak {
    title:"Weak"
    value:2
    competence: [Weak:60%]
}
level Moderate {
    title:"Moderate"
    value:3
    competence: [Weak:75%, Moderate: 60%]
 }
level Good {
    title:"Good"
    value:4
    competence: [Weak:85%, Moderate: 75%, Good:60%]
}
level Great {
    title:"Great"
    value:5
    competence: [Weak:95%, Moderate: 85%, Good:75%, Great: 60%]
}
